# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/isaachamann/Repositories/bare_gb/build

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/isaachamann/Repositories/bare_gb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/isaachamann/Repositories/bare_gb/CMakeFiles /Users/isaachamann/Repositories/bare_gb//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/isaachamann/Repositories/bare_gb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named baregb

# Build rule for target.
baregb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 baregb
.PHONY : baregb

# fast build rule for target.
baregb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baregb.dir/build.make CMakeFiles/baregb.dir/build
.PHONY : baregb/fast

#=============================================================================
# Target rules for targets named cpulib

# Build rule for target.
cpulib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpulib
.PHONY : cpulib

# fast build rule for target.
cpulib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpulib.dir/build.make CMakeFiles/cpulib.dir/build
.PHONY : cpulib/fast

src/src/cpu.o: src/src/cpu.c.o
.PHONY : src/src/cpu.o

# target to build an object file
src/src/cpu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpulib.dir/build.make CMakeFiles/cpulib.dir/src/src/cpu.c.o
.PHONY : src/src/cpu.c.o

src/src/cpu.i: src/src/cpu.c.i
.PHONY : src/src/cpu.i

# target to preprocess a source file
src/src/cpu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpulib.dir/build.make CMakeFiles/cpulib.dir/src/src/cpu.c.i
.PHONY : src/src/cpu.c.i

src/src/cpu.s: src/src/cpu.c.s
.PHONY : src/src/cpu.s

# target to generate assembly for a file
src/src/cpu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpulib.dir/build.make CMakeFiles/cpulib.dir/src/src/cpu.c.s
.PHONY : src/src/cpu.c.s

src/src/glad.o: src/src/glad.c.o
.PHONY : src/src/glad.o

# target to build an object file
src/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baregb.dir/build.make CMakeFiles/baregb.dir/src/src/glad.c.o
.PHONY : src/src/glad.c.o

src/src/glad.i: src/src/glad.c.i
.PHONY : src/src/glad.i

# target to preprocess a source file
src/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baregb.dir/build.make CMakeFiles/baregb.dir/src/src/glad.c.i
.PHONY : src/src/glad.c.i

src/src/glad.s: src/src/glad.c.s
.PHONY : src/src/glad.s

# target to generate assembly for a file
src/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baregb.dir/build.make CMakeFiles/baregb.dir/src/src/glad.c.s
.PHONY : src/src/glad.c.s

src/src/memory.o: src/src/memory.c.o
.PHONY : src/src/memory.o

# target to build an object file
src/src/memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpulib.dir/build.make CMakeFiles/cpulib.dir/src/src/memory.c.o
.PHONY : src/src/memory.c.o

src/src/memory.i: src/src/memory.c.i
.PHONY : src/src/memory.i

# target to preprocess a source file
src/src/memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpulib.dir/build.make CMakeFiles/cpulib.dir/src/src/memory.c.i
.PHONY : src/src/memory.c.i

src/src/memory.s: src/src/memory.c.s
.PHONY : src/src/memory.s

# target to generate assembly for a file
src/src/memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpulib.dir/build.make CMakeFiles/cpulib.dir/src/src/memory.c.s
.PHONY : src/src/memory.c.s

src/src/ppu.o: src/src/ppu.c.o
.PHONY : src/src/ppu.o

# target to build an object file
src/src/ppu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpulib.dir/build.make CMakeFiles/cpulib.dir/src/src/ppu.c.o
.PHONY : src/src/ppu.c.o

src/src/ppu.i: src/src/ppu.c.i
.PHONY : src/src/ppu.i

# target to preprocess a source file
src/src/ppu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpulib.dir/build.make CMakeFiles/cpulib.dir/src/src/ppu.c.i
.PHONY : src/src/ppu.c.i

src/src/ppu.s: src/src/ppu.c.s
.PHONY : src/src/ppu.s

# target to generate assembly for a file
src/src/ppu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpulib.dir/build.make CMakeFiles/cpulib.dir/src/src/ppu.c.s
.PHONY : src/src/ppu.c.s

src/tests/tests.o: src/tests/tests.c.o
.PHONY : src/tests/tests.o

# target to build an object file
src/tests/tests.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baregb.dir/build.make CMakeFiles/baregb.dir/src/tests/tests.c.o
.PHONY : src/tests/tests.c.o

src/tests/tests.i: src/tests/tests.c.i
.PHONY : src/tests/tests.i

# target to preprocess a source file
src/tests/tests.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baregb.dir/build.make CMakeFiles/baregb.dir/src/tests/tests.c.i
.PHONY : src/tests/tests.c.i

src/tests/tests.s: src/tests/tests.c.s
.PHONY : src/tests/tests.s

# target to generate assembly for a file
src/tests/tests.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baregb.dir/build.make CMakeFiles/baregb.dir/src/tests/tests.c.s
.PHONY : src/tests/tests.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... baregb"
	@echo "... cpulib"
	@echo "... src/src/cpu.o"
	@echo "... src/src/cpu.i"
	@echo "... src/src/cpu.s"
	@echo "... src/src/glad.o"
	@echo "... src/src/glad.i"
	@echo "... src/src/glad.s"
	@echo "... src/src/memory.o"
	@echo "... src/src/memory.i"
	@echo "... src/src/memory.s"
	@echo "... src/src/ppu.o"
	@echo "... src/src/ppu.i"
	@echo "... src/src/ppu.s"
	@echo "... src/tests/tests.o"
	@echo "... src/tests/tests.i"
	@echo "... src/tests/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

